const router = require('express').Router();
const mailer = require('nodemailer')
let AdminUser = require('../models/adminUser.model');
let generator = require('generate-password');

router.route('/').get((req,res) =>{
    AdminUser.find().then(adminUsers => res.json(adminUsers)).
    catch(err => res.status(400).json('Error: '+err));
});

router.route('/add').post((req,res) => {
    const name = req.body.name;
    const email = req.body.email;
    const password =  generator.generate({
        length: 10,
        numbers: true
    });
    const newAdminUser = new AdminUser({name,email,password});
    sendMail(name,email,password)
    newAdminUser.save()
        .then(() => res.json('User added!'))
        .catch(err => res.status(400).json('Error: ' + err));


});

router.route('/:id').get((req,res) =>{
    AdminUser.findById(req.params.id).
    then(adminUser => res.json(adminUser)).
    catch(err => res.status(400).json('Error' + err));
});

router.route('/:id').delete((req,res) => {
    AdminUser.findByIdAndDelete(req.params.id)
        .then(() => res.json('User is deleted'))
        .catch(err => res.status(400).json('Error '+err));
});

router.route('/:id').put((req,res)=> {
    AdminUser.findByIdAndUpdate(req.params.id)
        .then(adminUser => {
            adminUser.name = req.body.name;
            adminUser.email = req.body.email;

            adminUser.save()
                .then(() => res.json('User updated!'))
                .catch(err => res.status(400).json('Error: ' +err));
        })

        .catch(err => res.status(400).json('Error '+err));
});

const sendMail = (name,recipient,password)=>{
    const smtpTransport = mailer.createTransport({
        service: "Gmail",
        auth: {
            user:"nisansala.d9710@gmail.com",
            pass:"dilmigodakanda"

        }
    })
    var content = "This is an autogenerated mail by the blabla. This is to inform you that an account is created for you in the blabla website with the email "+recipient+ " . Please login to the website using the link and use email address as "+recipient+ " and password as " + password + " for your first login.";
    //document.getElementById("econtent").innerHTML = content;
    const data = {
        from:"CodeArmy <nisansala.d9710@gmail.com>",
        to:recipient,
        subject:'Registering to the blala website',
        text:content

    }
    smtpTransport.sendMail(data, function (err,res) {
        if(err){
            console.log(err)
        }
        else{
            console.log('email send successfully')
        }
        smtpTransport.close();
    })
}

module.exports = router;